name: flutter_callkit_example
description: Demonstrates how to use the flutter_callkit plugin.
publish_to: 'none'
version: 2.1.0

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_callkit_voximplant:
    path: ../
  uuid: ^4.5.3

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
   assets:
    - assets/voxlogo.png
