name: flutter_callkit_voximplant
description: Flutter SDK for CallKit integration to Flutter applications on iOS
version: 2.3.0
homepage: https://github.com/voximplant/flutter_callkit
repository: https://github.com/voximplant/flutter_callkit

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCallkitPlugin
